### ISSUE TITLE
Brother do you need payment gateways and channels both 3d and 2d...

### ISSUE THREAD

**Issue by shittih** [Mickerdx/MD_MoneyLaundry#1]
I do usdt deliveries 60/40 ratio https://t.me/cscscs69

**Comment by Mickerdx** [comment]
bro its a fivem script, i aint no illegal border jumper
________________________________
Van: shittih ***@***.***>
Verzonden: donderdag 2 mei 2024 15:53
Aan: Mickerdx/MD_MoneyLaundry ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [Mickerdx/MD_MoneyLaundry] Brother do you need payment gateways and channels both 3d and 2d... (Issue #1)


I do usdt deliveries 60/40 ratio https://t.me/cscscs69

**Comment by Sumpahpalapa** [comment]
> Saya melakukan pengiriman usdt rasio 60/40 https://t.me/cscscs69

You have payment gateway ? 3D or 2D ??
